# Site settings
site: Mylog
title: Mylog - Daily Log By Marzuki
keywords: marzuki, mylog
description: >-
  Mylog - Daily Log By Marzuki
lang: id-ID
timezone: Asia/Jakarta
repo: https://utaramas.github.io/pageone/ # site repo [optional]
google_verify: XXX # Put your Google Verification here
google_analytics: UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier: XXX

# Author settings
author:
  name: Marzuki
  bio: Hotel Affiliator <br> Posting Dulu, $$$$$$ Belakangan
  picture: assets/images/dealog.png
  github: utaramas # github username
  twitter: # twitter username
  facebook: # facebook username
  instagram: marzuki_id # instagram username
  youtube: https://youtube.com/ # youtube username
  linkedin: # linkedin username
  email: marzuki147@gmail.com # email adress

# URL settings
url: "https://utaramas.github.io/pageone/" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
